In [ ]:
# Package import

from datetime import datetime
import pandas as pd

In [ ]:
# Date period for export

start_date = datetime(2025,1,1)
end_date = datetime(2030,12,31)

date_range = pd.date_range(start_date,end_date)

date_df = pd.DataFrame(date_range, columns=["date"])

In [ ]:
# Check

date_df.head()

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03
3 2025-01-04
4 2025-01-05

In [ ]:
# Additional info in separated columns

date_df["year"] = date_df["date"].dt.year
date_df["month"] = date_df["date"].dt.month
date_df["day"] =date_df["date"].dt.day
date_df["day_of_week"] = date_df["date"].dt.dayofweek + 1 # Without adding +1, Monday would be considered as 0!
date_df["is_weekend"] = date_df["day_of_week"].isin([6,7])

In [ ]:
# Check

date_df.sample(10)

           date  year  month  day  day_of_week  is_weekend
912  2027-07-02  2027      7    2            5       False
1606 2029-05-26  2029      5   26            6        True
1046 2027-11-13  2027     11   13            6        True
474  2026-04-20  2026      4   20            1       False
1807 2029-12-13  2029     12   13            4       False
807  2027-03-19  2027      3   19            5       False
599  2026-08-23  2026      8   23            7        True
1977 2030-06-01  2030      6    1            6        True
819  2027-03-31  2027      3   31            3       False
2014 2030-07-08  2030      7    8            1       False

In [24]:
# CSV export

date_df.to_csv("dim_date", index=False)